# L01
## Mini Python Demo


REVISIONS||
---------||
2019-0128|CEF, initial. 
2019-0806|CEF, E19 ITMAL update. 

### Mini Python/Jupyternotebook demo

Build-in python array an Numpy arrays...

In [1]:
# import clause, imports numpy as the name 'np'
import numpy as np

# python build-in array
x = [[1, 2, 3], [4, 5, 6]]

# print using print-f-syntax, prefeed againts say print('x = ',x)
print(f'x = {x}')
print()
 
# create a numpy array
y = np.array( [[1.0, 2, 3, 4], [10, 20, 30, 42]] )

print(f'y = {y}')
print()
print(f'y.dtype={y.dtype}, y.itemsize={y.itemsize}, y.shape={y.shape}')
print()

print("indexing...like a (m x n) matrix")
print(y[0,1])  
print(y[0,-1]) # elem 0-from the 'right', strange but pythonic
print(y[0,-2]) # elem 1-from the 'right'

# print a column, but will display as 'row'
print(y[:,1])

print('\nOK')

x = [[1, 2, 3], [4, 5, 6]]

y = [[ 1.  2.  3.  4.]
 [10. 20. 30. 42.]]

y.dtype=float64, y.itemsize=8, y.shape=(2, 4)

indexing...like a (m x n) matrix
2.0
4.0
3.0
[ 2. 20.]

OK


#### Matrix multiplication

Just use Numpy as a matrix like class; create a (3 x 4) matrix and do some matrix operations on it... 

<img src="Figs/matrix.jpg" />

(NOTE: do not use `numpy.matrix`, <a href='https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html'>it is unfortunatly depricated.</a>)


In [2]:
x = np.array([ [2, -5, -11 ,0], [-9, 4, 6, 13], [4, 7, 12, -2]])

print(f'x={x}\ny.shape={x.shape}\n')
y = np.transpose(x)

# No direct *-oprator in numpy, 
#  x*y will throw ValueError: operands could not be broadcast together with shapes (3,4) (4,3)
#z=x*y

# numpy dot is a typically combo python function; 
#  inner-product if x and y are 1D arrays (vectors)
#  matrix multiplication if x and y are 2D arrays (matrices) 

z = np.dot(x, y)
print(f'the dot product, np.dot(x, y)={z}')

# alternatives to .dot:
#print(np.matmul(x, y))
#print(x @ y)

# the depricated numpy matrix 
mx = np.matrix(x)
my = np.matrix(y)
mz = mx*my;

print(f'\nmatrix type mult: mx*my={mz}')

x=[[  2  -5 -11   0]
 [ -9   4   6  13]
 [  4   7  12  -2]]
y.shape=(3, 4)

the dot product, np.dot(x, y)=[[ 150 -104 -159]
 [-104  302   38]
 [-159   38  213]]

matrix type mult: mx*my=[[ 150 -104 -159]
 [-104  302   38]
 [-159   38  213]]


#### Writing pythonic,robust code

Range-checks and fail-fast...

In [3]:
import sys, traceback

print('Writing pythonic,robust code: range-checks and fail-fast...')

# python do all kinds of range-checks: robust coding
#print(y[:,-5]) # will throw!

print('a pythonic assert..')
assert True==1, 'notice the lack of () in python asserts'

print('a try-catch block..')
try:
    print(y[:,-5])
except IndexError as e:
    print(f'cauth exception e="{e}"')
    traceback.print_exc(file=sys.stdout)
    print()
finally:
    print('finally executed last no matter what..')

Writing pythonic,robust code: range-checks and fail-fast...
a pythonic assert..
a try-catch block..
cauth exception e="index -5 is out of bounds for axis 1 with size 3"
Traceback (most recent call last):
  File "<ipython-input-3-15b8e7e2ae08>", line 13, in <module>
    print(y[:,-5])
IndexError: index -5 is out of bounds for axis 1 with size 3

finally executed last no matter what..
